// export const API = "http://localhost:4000";
export const API = "https://ecommerce-backend-0fue.onrender.com";

// [
//     {
//       "slug": "iPhone 9",
//       "name": "iPhone 9",
//       "description": "An apple mobile which is nothing like apple",
//       "price": 549,
//       "stock": 94,
//       "brand": "Apple",
//       "category": "smartphones",
//       "images": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
//     },
//     {
//       "name": "iPhone X",
//       "slug": "iPhone X",
//       "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
//       "price": 899,
//       "stock": 34,
//       "category": "smartphones",
//       "images": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
//     },
//     {
//       "slug": "Samsung Universe 9",
//       "name": "Samsung Universe 9",
//       "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
//       "price": 1249,
//       "stock": 36,
//       "category": "smartphones",
//       "images": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
//     },
//     {
//       "slug": "OPPOF19",
      
//       "name": "OPPOF19",
//       "description": "OPPO F19 is officially announced on April 2021.",
//       "price": 280,
//       "stock": 123,
//       "category": "smartphones",
//       "images": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
//     },
//     {
//       "name": "Huawei P30",
      
//       "slug": "Huawei P30",
//       "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
//       "price": 499,
//       "stock": 32,
//       "category": "smartphones",
//       "images": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
//     },
//     {  
//       "slug": "MacBook Pro",
//       "name": "MacBook Pro",
//       "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
//       "price": 1749,
//       "stock": 83,
//       "category": "laptops",
//       "images": "https://i.dummyjson.com/data/products/6/thumbnail.png",
//      },
//     {
//       "slug": "Samsung Galaxy Book",
      
//       "name": "Samsung Galaxy Book",
//       "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
//       "price": 1499,
//       "stock": 50,
//       "category": "laptops",
//       "images": "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
//      },
//     {
//       "slug": "Microsoft Surface Laptop 4",
      
//       "name": "Microsoft Surface Laptop 4",
//       "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
//       "price": 1499,
//       "stock": 68,
//       "category": "laptops",
//       "images": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
//      },
//     {
//       "slug": "Infinix INBOOK",
//       "name": "Infinix INBOOK",
//       "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
//       "price": 1099,
//       "stock": 96,
//       "category": "laptops",
//       "images": "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
//      },
//     {
//       "slug": "HP Pavilion 15-DK1056WM",
//       "name": "HP Pavilion 15-DK1056WM",
//       "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
//       "price": 1099,
//       "stock": 89,
//       "category": "laptops",
//       "images": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
//      },
//     {
//       "slug": "perfume Oil",
//       "name": "perfume Oil",
//       "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
//       "price": 13,
//       "stock": 65,
//       "category": "fragrances",
//       "images": "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
//      },
//     {
//       "slug": "Brown Perfume",
//       "name": "Brown Perfume",
//       "description": "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
//       "price": 40,
//       "stock": 52,
//       "category": "fragrances",
//       "images": "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
//      },
//     {
//       "slug": "Fog Scent Xpressio Perfume",
//       "name": "Fog Scent Xpressio Perfume",
//       "description": "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
//       "price": 13,
//       "stock": 61,
//       "category": "fragrances",
//       "images": "https://i.dummyjson.com/data/products/13/thumbnail.webp",
//      },
//     {
//       "slug": "Non-Alcoholic Concentrated Perfume Oil",
      
//       "name": "Non-Alcoholic Concentrated Perfume Oil",
//       "description": "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
//       "price": 120,
//       "stock": 114,
//       "category": "fragrances",
//       "images": "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
//      },
//     {
//       "slug": "Eau De Perfume Spray",
//       "name": "Eau De Perfume Spray",
//       "description": "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
//       "price": 30,
//       "stock": 105,
//       "category": "fragrances",
//       "images": "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
//      },
//     {
//       "slug": "Hyaluronic Acid Serum",
//       "name": "Hyaluronic Acid Serum",
//       "description": "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
//       "price": 19,
//       "stock": 110,
//       "category": "skincare",
//       "images": "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
//      },
//     {
//       "slug": "Tree Oil 30ml",
//       "name": "Tree Oil 30ml",
//       "description": "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
//       "price": 12,
//       "stock": 78,
//       "category": "skincare",
//       "images": "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
//      },
//     {
//       "slug": "Oil Free Moisturizer 100ml",
//       "name": "Oil Free Moisturizer 100ml",
//       "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
//       "price": 40,
//       "stock": 88,
//       "category": "skincare",
//       "images": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
//      },
//     {
//       "slug": "Skin Beauty Serum.",
//       "name": "Skin Beauty Serum.",
//       "description": "Product slug: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
//       "price": 46,
//       "stock": 54,
//       "category": "skincare",
//       "images": "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
//      },
//     {
//       "slug": "Freckle Treatment Cream- 15gm",
//       "name": "Freckle Treatment Cream- 15gm",
//       "description": "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
//       "price": 70,
//       "stock": 140,
//       "category": "skincare",
//       "images": "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
//      },
//     {
//       "slug": "- Daal Masoor 500 grams",
//       "name": "- Daal Masoor 500 grams",
//       "description": "Fine quality Branded Product Keep in a cool and dry place",
//       "price": 20,
//       "stock": 133,
//       "category": "groceries",
//       "images": "https://i.dummyjson.com/data/products/21/thumbnail.png",
//      },
//     {
//      "slug": "Elbow Macaroni - 400 gm",
//       "name": "Elbow Macaroni - 400 gm",
//       "description": "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
//       "price": 14,
//       "stock": 146,
//       "category": "groceries",
//       "images": "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
//     },
//     {
//       "slug": "Orange Essence Food Flavou",
//       "name": "Orange Essence Food Flavou",
//       "description": "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
//       "price": 14,
//       "stock": 26,
//       "category": "groceries",
//       "images": "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
//     },
//     {
//       "slug": "cereals muesli fruit nuts",
//       "name": "cereals muesli fruit nuts",
//       "description": "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
//       "price": 46,
//       "stock": 113,
//       "category": "groceries",
//       "images": "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
//     },
//     {
//       "slug": "Gulab Powder 50 Gram",
//       "name": "Gulab Powder 50 Gram",
//       "description": "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
//       "price": 70,
//       "stock": 47,
//       "category": "groceries",
//       "images": "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
//     },
//     {
//       "slug": "Plant Hanger For Home",
//       "name": "Plant Hanger For Home",
//       "description": "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
//       "price": 41,
//       "stock": 131,
//       "category": "home-decoration",
//       "images": "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
//     },
//     {
//       "slug": "Flying Wooden Bird",
//       "name": "Flying Wooden Bird",
//       "description": "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
//       "price": 51,
//       "stock": 17,
//       "category": "home-decoration",
//       "images": "https://i.dummyjson.com/data/products/27/thumbnail.webp",
//     },
//     {
//       "slug": "3D Embellishment Art Lamp",
//       "name": "3D Embellishment Art Lamp",
//       "description": "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
//       "price": 20,
//       "stock": 54,
//       "category": "home-decoration",
//       "images": "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
//     },
//     {
//       "slug": "Handcraft Chinese style",
//       "name": "Handcraft Chinese style",
//       "description": "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
//       "price": 60,
//       "stock": 7,
//       "category": "home-decoration",
//       "images": "https://i.dummyjson.com/data/products/29/thumbnail.webp",
//     },
//     {
//       "slug": "Key Holder",
//       "name": "Key Holder",
//       "description": "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
//       "price": 30,
//       "stock": 54,
//       "category": "home-decoration",
//       "images": "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
//     }]